### PR TITLE
TrustedCallbackInterface implementation

### LINKED ISSUE #33: Render callback must implement TrustedCallbackInterface
I've got a site crashing in `Content > Media`, but only if you try to edit a video. On this site all videos are Youtube embeds.

The error references this 8.8 feature:
https://www.drupal.org/node/2966725

It looks like the MediaForm class needs to `implement TrustedCallbackInterface` which requires a new function:
```
  /**
   * {@inheritdoc}
   */

  public static function trustedCallbacks() {
    return ['renderPreview'];
  }

  ```

### PR DESCRIPTION
**Pull request by spncr**
This would fix #33 

@mariacha do you have time for a review? I think it would be quick for you 🤞🏻

@katieescoto I guess we've got a small pile of these to roll into a new release soon?

### CODE REVIEW

File: src/Form/MediaForm.php [hunk 1]
```diff
@@ -5,16 +5,25 @@
 use Drupal\Component\Utility\NestedArray;
 use Drupal\Core\Form\FormStateInterface;
 use Drupal\bene_media\MediaHelper as Helper;
+use Drupal\Core\Security\TrustedCallbackInterface;
```
Comment (mariacha) [inline src/Form/MediaForm.php:8]: If I'm reading the documentation correctly, this object was introduced in Drupal 8.8: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Security%21TrustedCallbackInterface.php/interface/TrustedCallbackInterface/8.8.x

So let's update that in the module's .info file: https://github.com/thinkshout/bene_media/blob/8.x-2.x-bene/bene_media.info.yml#L7

**Review by mariacha — APPROVED** [review]
This seems good -- one small suggestion.

File: src/Form/MediaForm.php (hunk 1 above)
Comment (spncr) [reply src/Form/MediaForm.php:8]: Perfect, thank you and merged!
